# Super Store Sales Analysis

## Phase 1 — Setup

### Set up Environment

In [124]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Phase 2 — Data loading and cleaning

### Load and Inspect

In [125]:
df_train = pd.read_csv("../data/train.csv", encoding = "latin1")
df_super_store = pd.read_csv("../data/SampleSuperstore.csv", encoding = "latin1")

common_cols = ["Ship Mode", "Segment", "Country", "City", "State", "Postal Code", "Region", "Category", "Sub-Category", "Sales"]

df_master = pd.merge(df_train, df_super_store[common_cols + ["Quantity", "Discount", "Profit"]], on = common_cols, how = "left")
print(df_master.head())

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0     42420.0   South  FUR-BO-10001798        Furniture    Bookcases
1     42420.0   South  FUR-CH-10000454        Furniture       Chairs
2     90036.0    West  OFF-LA-10000240  Office Supplies       Labels
3     33311.0   South  FUR-TA-10000577        Furniture       Tables
4     33311.0   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600       2.0
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400       3.0
2  Self-Adhesive Address Labels for Typewriters b...   14.6200       2.0
3      Bretford CR4500 Series Slim Rectangular Table  957.5775       5.0
4                     Eldon Fold 'N Roll Cart System   22.3680       2.0

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

In [126]:
df_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 9846 entries, 0 to 9845
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9846 non-null   int64
 1   Order ID       9846 non-null   str
 2   Order Date     9846 non-null   str
 3   Ship Date      9846 non-null   str
 4   Ship Mode      9846 non-null   str
 5   Customer ID    9846 non-null   str
 6   Customer Name  9846 non-null   str
 7   Segment        9846 non-null   str
 8   Country        9846 non-null   str
 9   City           9846 non-null   str
 10  State          9846 non-null   str
 11  Postal Code    9835 non-null   float64
 12  Region         9846 non-null   str
 13  Product ID     9846 non-null   str
 14  Category       9846 non-null   str
 15  Sub-Category   9846 non-null   str
 16  Product Name   9846 non-null   str
 17  Sales          9846 non-null   float64
 18  Quantity       9835 non-null   float64
 19  Discount       9835 non-null   float64
 20  Profit         9835 non-null   float64
dtypes: float64(5), int64(1), str(15)
memory usage: 1.6 MB

In [127]:
df_master.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9846.000000,9835.000000,9846.000000,9835.000000,9835.000000,9835.000000
mean,4901.153260,55320.557092,229.977340,3.786985,0.156708,28.192512
std,2828.302535,32052.283897,625.329776,2.215939,0.206786,235.326727
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2455.250000,23223.000000,17.142500,2.000000,0.000000,1.719300
50%,4900.500000,59405.000000,53.946000,3.000000,0.200000,8.526000
75%,7350.750000,90008.000000,209.976750,5.000000,0.200000,29.085000
max,9800.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

### Fix Data Types

In [128]:
df_master["Order Date"] = pd.to_datetime(df_master["Order Date"], format = "%d/%m/%Y")
print(f"Datatype of Order Date Column: {df_master["Order Date"].dtype}")

df_master["Ship Date"] = pd.to_datetime(df_master["Ship Date"], format = "%d/%m/%Y")
print(f"Datatype of Ship Date Column: {df_master["Ship Date"].dtype}")

Datatype of Order Date Column: datetime64[us]
Datatype of Ship Date Column: datetime64[us]

In [129]:
df_master[df_master["Profit"].isnull()]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2241,2235,CA-2018-104066,2018-12-05,2018-12-10,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,...,NaN,East,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,205.03,NaN,NaN,NaN
5298,5275,CA-2016-162887,2016-11-07,2016-11-09,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,...,NaN,East,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20,NaN,NaN,NaN
8840,8799,US-2017-150140,2017-04-06,2017-04-10,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,...,NaN,East,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75,NaN,NaN,NaN
9188,9147,US-2017-165505,2017-01-23,2017-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,...,NaN,East,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,99.98,NaN,NaN,NaN
9189,9148,US-2017-165505,2017-01-23,2017-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,...,NaN,East,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04,NaN,NaN,NaN
9190,9149,US-2017-165505,2017-01-23,2017-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,...,NaN,East,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Cart,1564.29,NaN,NaN,NaN
9430,9387,US-2018-127292,2018-01-19,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,...,NaN,East,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92,NaN,NaN,NaN
9431,9388,US-2018-127292,2018-01-19,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,...,NaN,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28,NaN,NaN,NaN
9432,9389,US-2018-127292,2018-01-19,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,...,NaN,East,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94,NaN,NaN,NaN
9433,9390,US-2018-127292,2018-01-19,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,...,NaN,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04,NaN,NaN,NaN
9787,9742,CA-2016-117086,2016-11-08,2016-11-12,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,...,NaN,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.90,NaN,NaN,NaN

### Handle Missing and Duplicates

In [130]:
null_count_super_store = df_master.isnull().sum()
print("null in super store:", null_count_super_store)

df_master.dropna(subset = ["Profit"], inplace = True)

null_count_super_store_2 = df_master.isnull().sum()
print("null in super store 2:", null_count_super_store_2)

duplicates_super_store = df_master.duplicated()
print("duplicates in super store:", duplicates_super_store) # no duplicates

df_master.drop_duplicates()
print("Info: ", df_master.info()) # no duplicates

null in super store: Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity         11
Discount         11
Profit           11
dtype: int64
null in super store 2: Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64
duplicates in super store: 0       False
1       False
2       False
3       False
4       False
        ...
9841    False
9842    False
9843    False
9844    False
9845    False
Length: 9835, dtype: bool
<class 'pandas.DataFrame'>
Index: 9835 entries, 0 to 9845
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9835 non-null   int64
 1   Order ID       9835 non-null   str
 2   Order Date     9835 non-null   datetime64[us]
 3   Ship Date      9835 non-null   datetime64[us]
 4   Ship Mode      9835 non-null   str
 5   Customer ID    9835 non-null   str
 6   Customer Name  9835 non-null   str
 7   Segment        9835 non-null   str
 8   Country        9835 non-null   str
 9   City           9835 non-null   str
 10  State          9835 non-null   str
 11  Postal Code    9835 non-null   float64
 12  Region         9835 non-null   str
 13  Product ID     9835 non-null   str
 14  Category       9835 non-null   str
 15  Sub-Category   9835 non-null   str
 16  Product Name   9835 non-null   str
 17  Sales          9835 non-null   float64
 18  Quantity       9835 non-null   float64
 19  Discount       9835 non-null   float64
 20  Profit         9835 non-null   float64
dtypes: datetime64[us](2), float64(5), int64(1), str(13)
memory usage: 1.7 MB
Info:  None

### Feature Engineering

In [131]:
df_master["Month"] = df_master["Order Date"].dt.to_period("M")
df_master["Year"] = df_master["Order Date"].dt.year
df_master["Profit Margin(%)"] = df_master["Profit"] / df_master["Sales"] * 100

print(df_master.shape)

(9835, 24)

## Phase 3 — Core analysis (3 required outputs)

### Monthly Revenue

In [132]:
monthly_revenue = (
    df_master
    .groupby("Month")["Sales"]
    .sum()
    .reset_index()
    .rename(columns = {"Sales": "Monthly Revenue"})
)
monthly_revenue

      Month  Monthly Revenue
0   2015-01       14205.7070
1   2015-02        4519.8920
2   2015-03       55205.7970
3   2015-04       28515.5190
4   2015-05       23657.6950
5   2015-06       34322.9356
6   2015-07       33830.6630
7   2015-08       27133.0885
8   2015-09       81623.5268
9   2015-10       31453.3930
10  2015-11       77974.9807
11  2015-12       68190.2665
12  2016-01       18066.9576
13  2016-02       11951.4110
14  2016-03       32339.3184
15  2016-04       34154.4685
16  2016-05       29975.9345
17  2016-06       23647.3260
18  2016-07       28621.2190
19  2016-08       36818.3422
20  2016-09       63133.6060
21  2016-10       31417.2595
22  2016-11       70186.4315
23  2016-12       74543.6012
24  2017-01       16870.1810
25  2017-02       23068.7850
26  2017-03       51188.8190
27  2017-04       37385.0170
28  2017-05       56656.9080
29  2017-06       39740.0380
30  2017-07       38320.7830
31  2017-08       30561.6403
32  2017-09       69455.1009
33  2017-10       59598.5850
34  2017-11       79469.4258
35  2017-12       96104.9610
36  2018-01       42865.2140
37  2018-02       19920.9974
38  2018-03       58885.5528
39  2018-04       35541.9101
40  2018-05       43903.4182
41  2018-06       48190.7277
42  2018-07       44838.0640
43  2018-08       62837.8480
44  2018-09       86152.8880
45  2018-10       77516.6912
46  2018-11      118039.2670
47  2018-12       82825.3588

### Top Products

In [133]:
df_master.head()
top_products = (
    df_master.groupby("Product Name")["Row ID"]
    .count()
    .reset_index()
    .rename(columns = {"Row ID": "Total Product Sale"})
    .sort_values("Total Product Sale", ascending = False)
)
top_products.head(10)

                                           Product Name  Total Product Sale
1491                                    Staple envelope                  47
1497                                            Staples                  46
536                                   Easy-staple paper                  44
258                             Avery Non-Stick Binders                  20
1509                            Storex Dura Pro Binders                  19
1498                            Staples in misc. colors                  18
1494                                     Staple remover                  18
940                          KI Adjustable-Height Table                  17
991   Logitech 910-002974 M325 Wireless Mouse for We...                  16
1495                         Staple-based wall hangings                  16

### Profit Analysis

In [139]:
region_profit = (
    df_master
    .groupby("Region")[["Sales", "Profit"]]
    .sum()
    .reset_index()
)
region_profit["Profit Margin(%)"] = (region_profit["Profit"] / region_profit["Sales"] * 100).round(2)
print(region_profit.sort_values("Profit Margin(%)", ascending = False))

    Region        Sales       Profit  Profit Margin(%)
3     West  710624.0605  105534.4889             14.85
1     East  661487.3040   87371.0954             13.21
2    South  389697.2790   46384.9713             11.90
0  Central  493618.8772   37982.8045              7.69

In [140]:
category_profit = (
    df_master
    .groupby("Category")[["Sales", "Profit"]]
    .sum()
    .reset_index()
)
category_profit["Profit Margin(%)"] = (category_profit["Profit"] / category_profit["Sales"] * 100).round(2)
print(category_profit.sort_values("Profit Margin(%)", ascending = False))

          Category        Sales       Profit  Profit Margin(%)
2       Technology  826535.9530  142839.2092             17.28
1  Office Supplies  703966.1280  118645.4755             16.85
0        Furniture  724925.4397   15788.6754              2.18

In [142]:
segment_profit = (
    df_master
    .groupby("Segment")[["Sales", "Profit"]]
    .sum()
    .reset_index()
)
segment_profit["Profit Margin(%)"] = (segment_profit["Profit"] / segment_profit["Sales"] * 100).round(2)
print(segment_profit.sort_values("Profit Margin(%)", ascending = False))

       Segment         Sales       Profit  Profit Margin(%)
2  Home Office  4.244084e+05   59440.8044             14.01
1    Corporate  6.824413e+05   86657.8098             12.70
0     Consumer  1.148578e+06  131174.7459             11.42